import OpenAI from "openai";

// Interface for guidance steps
interface GuidanceStep {
  step: string;
  visualDescription: string;
}

// Interface for guidance result
interface GuidanceResult {
  success: boolean;
  text: string;
  feature: string;
}

// OpenAI client if API key is available
let openai: OpenAI | null = null;
if (process.env.OPENAI_API_KEY) {
  openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  console.log("OpenAI service initialized for accessibility features");
} else {
  console.warn("OPENAI_API_KEY not found, accessibility service will use predefined responses");
}

// Predefined guidance content for security features
const guidanceContent: Record<string, { 
  standard: string, 
  forDeaf: string,
  steps: GuidanceStep[]
}> = {
  "multi-factor-authentication": {
    standard: `Multi-factor authentication adds an extra layer of security to your account by requiring multiple forms of verification. This typically includes something you know (like a password), something you have (like a mobile device), and sometimes something you are (like a fingerprint). 

When enabled, after entering your password, you'll be asked to provide a second form of verification such as a code sent to your phone or generated by an authenticator app. This prevents unauthorized access even if your password is compromised.`,
    
    forDeaf: `Multi-factor authentication (MFA) is a security feature that requires multiple proofs of identity before granting access. Instead of just using a password (single factor), MFA requires additional verification.

VISUAL EXPLANATION:
- First verification: Enter your password (something you know)
- Second verification: Scan a QR code with your phone, or enter a code from an authentication app (something you have)
- Sometimes a third verification: Use your fingerprint or face scan (something you are)

Even if someone gets your password, they still can't access your account without your physical device or biometric data. MFA provides a significantly stronger security barrier than passwords alone.`,
    
    steps: [
      {
        step: "Navigate to Account Settings",
        visualDescription: "Look for a gear or profile icon, usually in the top-right corner of the screen. Click it to open a dropdown menu, then select 'Account Settings' or 'Security Settings'."
      },
      {
        step: "Find Security Options",
        visualDescription: "In the settings menu, look for a section labeled 'Security', 'Account Security', or 'Login & Security'. This section will have options related to protecting your account."
      },
      {
        step: "Enable Multi-Factor Authentication",
        visualDescription: "Find the toggle switch or checkbox labeled 'Multi-Factor Authentication' or '2FA'. Click to enable it. The switch will typically change color or position when activated."
      },
      {
        step: "Choose Verification Method",
        visualDescription: "A list of verification options will appear. These usually include: 'SMS/Text Message', 'Authenticator App', or 'Security Key'. Select your preferred method by clicking on it."
      },
      {
        step: "Complete Setup Process",
        visualDescription: "Follow the on-screen instructions to complete the setup. If using an authenticator app, you'll see a QR code to scan. If using SMS, you'll need to enter your phone number and verify with a code."
      }
    ]
  },
  
  "biometric-verification": {
    standard: `Biometric verification uses your unique biological characteristics to confirm your identity. Common biometric methods include fingerprint scanning, facial recognition, and voice pattern analysis.

The system captures your biometric data and creates a secure digital template. When you authenticate, the system compares your live biometric data with the stored template to verify your identity. This offers a convenient and highly secure alternative to passwords since biometric traits are unique to you and difficult to replicate.`,
    
    forDeaf: `Biometric verification uses your unique physical characteristics to prove your identity.

VISUAL EXPLANATION:
- The system captures unique aspects of your body: fingerprints, face shape/features, or eye patterns
- These characteristics are converted into a secure digital template (not an actual image)
- When you sign in, the system compares your live scan with the stored template
- If they match closely enough, you're verified

Unlike passwords that can be forgotten or stolen, your biometric features are always with you and extremely difficult for others to duplicate. For deaf users, biometric verification offers a particularly accessible security method that doesn't rely on voice or hearing.`,
    
    steps: [
      {
        step: "Access Biometric Settings",
        visualDescription: "On the security settings page, look for an option labeled 'Biometric Verification', 'Biometric Login', or similar. This section will have an icon showing a fingerprint, face outline, or eye."
      },
      {
        step: "Select Biometric Type",
        visualDescription: "Choose which biometric method you want to use: fingerprint (shows a fingerprint icon), facial recognition (shows a face outline), or iris scan (shows an eye symbol)."
      },
      {
        step: "Position Yourself Correctly",
        visualDescription: "Follow the on-screen guide showing how to position yourself. For face scans, center your face in the outlined area. For fingerprints, place your finger on the designated sensor area."
      },
      {
        step: "Complete the Scan",
        visualDescription: "Hold still while the scan completes. A progress indicator will show the scanning status. For fingerprints, you may need to place your finger multiple times from different angles."
      },
      {
        step: "Verify Success",
        visualDescription: "A green checkmark or success message will appear when your biometric data has been successfully registered. The screen will show 'Biometric Verification Enabled' with a toggle switch in the ON position."
      }
    ]
  },
  
  "encryption": {
    standard: `End-to-end encryption secures your data by encoding it so that only the intended recipients can access it. When you send encrypted data, it's scrambled using complex mathematical algorithms, making it unreadable to anyone who might intercept it.

The data remains encrypted throughout its journey and is only decrypted when it reaches its destination. This ensures that even if someone gains unauthorized access to the servers or transmission channels, they cannot read your sensitive information.`,
    
    forDeaf: `End-to-end encryption protects your information by converting it into a secret code that only the right person can unlock.

VISUAL EXPLANATION:
- Your message or data starts as normal text on your device
- Before sending, it gets converted into scrambled code using a special key
- While traveling over the internet, the data remains scrambled and unreadable
- Only the intended recipient has the matching key to unscramble and read it
- No one in between (not even the service provider) can see what you sent

This means your private conversations, financial details, and personal information stay protected from hackers, companies, and anyone else who might try to view your data without permission.`,
    
    steps: [
      {
        step: "Go to Privacy Settings",
        visualDescription: "Navigate to the 'Privacy' or 'Security & Privacy' section in your settings menu. Look for a section with a lock icon or shield symbol indicating security features."
      },
      {
        step: "Find Encryption Options",
        visualDescription: "Look for a setting labeled 'Encryption', 'Data Encryption', or 'End-to-End Encryption'. It will typically have a lock or key icon next to it."
      },
      {
        step: "Enable Encryption",
        visualDescription: "Click the toggle switch to turn on encryption. The switch will change from gray to a highlighted color (often green or blue) when active."
      },
      {
        step: "Create Encryption Password (if required)",
        visualDescription: "Some systems will ask you to create a special encryption password or PIN. You'll see a form with password strength indicators and confirmation fields."
      },
      {
        step: "Verify Encryption Status",
        visualDescription: "Look for visual indicators showing encryption is active: a closed padlock icon, 'Encryption Enabled' text in green, or a shield with a checkmark. These symbols confirm your data is now protected."
      }
    ]
  },
  
  "vulnerability-scanning": {
    standard: `Vulnerability scanning is a security process that examines your system for potential security weaknesses that could be exploited by attackers. The scanner systematically checks your software, networks, and configurations against a database of known vulnerabilities.

When a scan is completed, you'll receive a report detailing any vulnerabilities found, their severity levels, and recommendations for remediation. Regular scanning helps identify security issues before they can be exploited, allowing you to strengthen your defenses proactively.`,
    
    forDeaf: `Vulnerability scanning is like a security inspection that checks your system for weak points that hackers could exploit.

VISUAL EXPLANATION:
- The scanner examines your software, network settings, and security configurations
- It compares what it finds against a database of known security problems
- Each potential weakness is identified and categorized by risk level
- Results are displayed in a visual report with color-coding: red (critical), orange (high), yellow (medium), green (low)
- The report includes specific recommendations for fixing each issue

Regular scanning helps you discover and fix security problems before hackers can find and exploit them. Think of it as finding the weak spots in your digital fence before intruders can use them to break in.`,
    
    steps: [
      {
        step: "Access Security Center",
        visualDescription: "Navigate to the 'Security Center' or 'Security Dashboard' section. Look for a shield icon or security-related symbol in the main menu."
      },
      {
        step: "Locate Vulnerability Scanner",
        visualDescription: "Find the 'Vulnerability Scanner', 'Security Scan', or 'System Check' option. It typically shows an icon of a magnifying glass over a shield or computer."
      },
      {
        step: "Configure Scan Settings",
        visualDescription: "A settings panel will appear with options to select what to scan. Checkboxes allow you to choose scan targets (software, files, network). You can also set the scan intensity using a slider from 'Basic' to 'Thorough'."
      },
      {
        step: "Initiate the Scan",
        visualDescription: "Click the prominent 'Start Scan' or 'Run Scan' button. A progress bar will appear showing the scan completion percentage and current area being scanned."
      },
      {
        step: "Review Results and Take Action",
        visualDescription: "After completion, a summary screen appears showing color-coded results: red sections for critical issues, yellow for warnings, green for passed checks. Each item has an 'Info' button for details and a 'Fix' or 'Repair' button to resolve issues."
      }
    ]
  },
  
  "security-badges": {
    standard: `Security badges are achievements awarded to users who complete specific security-related actions or reach certain security milestones. They serve as visual indicators of your commitment to good security practices and your security knowledge level.

Badges can be earned by enabling security features, completing security training, maintaining a clean security record, and following best practices. They are displayed on your profile and can enhance your reputation by demonstrating your dedication to security.`,
    
    forDeaf: `Security badges are visual awards you earn by completing security actions and demonstrating good security practices.

VISUAL EXPLANATION:
- Each badge has a unique design that represents a specific security achievement
- Badges are displayed on your profile in a dedicated 'Achievements' or 'Security Status' section
- Different badge levels (Bronze, Silver, Gold, Platinum) show your progression
- Badges are organized by categories: Authentication, Data Protection, Financial Security, etc.
- Hovering over or clicking a badge reveals details about how you earned it

These badges serve multiple purposes:
1. They visually track your security progress
2. They encourage you to enable more security features
3. They demonstrate your security commitment to others
4. They provide a clear path to improving your account's protection level`,
    
    steps: [
      {
        step: "Find Your Security Profile",
        visualDescription: "Navigate to your profile section and look for 'Security Profile', 'Security Status', or 'Achievements'. This area typically has shield or badge icons and shows your current security level with a progress indicator."
      },
      {
        step: "View Available Badges",
        visualDescription: "You'll see a grid or list of badge icons. Earned badges appear in full color while unearned badges appear grayed out or as outlines. Each badge has a distinct icon representing its security category."
      },
      {
        step: "Check Badge Requirements",
        visualDescription: "Click on any badge to see its details. A pop-up card appears showing: the badge name, description, specific requirements to earn it, and your current progress with a percentage or fraction (e.g., '2/3 tasks completed')."
      },
      {
        step: "Complete Badge Tasks",
        visualDescription: "For each badge, you'll see a checklist of required actions. Completed items show a green checkmark, while pending items show an empty circle or arrow button that takes you directly to where you can complete that task."
      },
      {
        step: "Display Your Earned Badges",
        visualDescription: "Once earned, badges appear in your public profile. Toggle switches let you control which badges are visible to others. A 'Showcase' feature lets you pin your most important badges at the top of your profile."
      }
    ]
  },
  
  "secure-payments": {
    standard: `Secure payments protect your financial transactions by implementing multiple layers of security. These include encryption of payment data, secure authentication processes, fraud detection systems, and compliance with industry security standards.

When making a secure payment, your sensitive financial information is protected from interception and unauthorized access. The system also verifies the transaction's legitimacy through various checks to prevent fraud. This comprehensive approach safeguards both your financial data and your funds.`,
    
    forDeaf: `Secure payments protect your financial transactions with multiple safety measures to prevent fraud and data theft.

VISUAL EXPLANATION:
- Your payment information (card number, etc.) is encrypted (scrambled) immediately when entered
- The payment system verifies your identity through multiple checks
- Suspicious activity triggers visual alerts and additional verification steps
- Transaction details are continuously monitored for unusual patterns
- Visual confirmation appears when a transaction is successfully secured

The system works behind the scenes to protect your money and financial information. It combines encryption technology, identity verification, and continuous monitoring to create multiple defensive layers against fraudsters and hackers.`,
    
    steps: [
      {
        step: "Choose Secure Payment Method",
        visualDescription: "On the checkout page, look for payment options displaying security symbols: padlock icons, 'Secure Payment' badges, or trusted payment provider logos (PayPal, Apple Pay, etc.). These visual indicators show which methods offer enhanced protection."
      },
      {
        step: "Enter Payment Details Safely",
        visualDescription: "Notice the secure form for entering card details: green padlock in the address bar, https:// prefix, and a security indicator showing the connection is encrypted. The form highlights each field as you complete it, with real-time validation."
      },
      {
        step: "Verify Your Identity",
        visualDescription: "A verification screen appears requiring additional authentication. This may show a fingerprint icon (for biometric verification), a code entry field (for 2FA codes), or a redirect to your banking app. A progress indicator shows where you are in the verification process."
      },
      {
        step: "Review Security Features",
        visualDescription: "The payment confirmation screen displays security features activated for your transaction: encryption symbol, fraud protection shield, purchase protection icon, and transaction ID. Visual badges indicate which protections are active."
      },
      {
        step: "Confirm and Monitor",
        visualDescription: "After payment, a success screen appears with a green checkmark and transaction reference number. You'll receive a visual receipt showing security verification details and instructions for monitoring the transaction through a secure dashboard."
      }
    ]
  }
};

// Service for handling accessibility features
class AccessibilityService {
  async getGuidanceForFeature(feature: string, isDeaf: boolean = false): Promise<GuidanceResult> {
    // Check if we have predefined content for this feature
    if (guidanceContent[feature]) {
      return {
        success: true,
        text: isDeaf ? guidanceContent[feature].forDeaf : guidanceContent[feature].standard,
        feature
      };
    }
    
    // If OpenAI is available and we don't have predefined content, generate it
    if (openai) {
      try {
        // Construct a prompt based on whether the user is deaf
        const prompt = isDeaf
          ? `Create a clear, visually-focused explanation of the security feature "${feature}" specifically for deaf users. Use the phrase "VISUAL EXPLANATION:" followed by a bullet list of how the feature works visually. Focus on what users will see on screen and how visual cues indicate the feature is working. Avoid auditory descriptions.`
          : `Explain the security feature "${feature}" in simple terms. Describe what it is, how it works, and why it's important for security. Keep the explanation under 250 words and focus on plain language without technical jargon.`;

        const response = await openai.chat.completions.create({
          model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
          messages: [
            { 
              role: "system", 
              content: "You are an accessibility specialist who explains security concepts clearly."
            },
            { 
              role: "user", 
              content: prompt
            }
          ],
          temperature: 0.7,
          max_tokens: 500
        });

        const generatedText = response.choices[0].message.content;
        
        return {
          success: true,
          text: generatedText,
          feature
        };
      } catch (error) {
        console.error('Error generating guidance with OpenAI:', error);
        // Fall back to a generic response
        return {
          success: false,
          text: `We're sorry, but we currently don't have specific guidance available for the "${feature}" feature. Please try again later or contact support for assistance.`,
          feature
        };
      }
    }
    
    // Fallback for when OpenAI is not available and we don't have predefined content
    return {
      success: false,
      text: `We're sorry, but we currently don't have specific guidance available for the "${feature}" feature. Please try again later or contact support for assistance.`,
      feature
    };
  }

  async getVisualGuidanceSteps(feature: string): Promise<GuidanceStep[]> {
    // Check if we have predefined steps for this feature
    if (guidanceContent[feature] && guidanceContent[feature].steps) {
      return guidanceContent[feature].steps;
    }
    
    // If OpenAI is available and we don't have predefined steps, generate them
    if (openai) {
      try {
        const response = await openai.chat.completions.create({
          model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
          messages: [
            { 
              role: "system", 
              content: "You are an accessibility specialist who creates clear, visually-focused guidance steps. Format your response as a JSON array of objects with 'step' and 'visualDescription' properties."
            },
            { 
              role: "user", 
              content: `Create a step-by-step visual guide for using the security feature "${feature}". Include 5 steps, each with a brief title and a detailed visual description of what the user will see on screen. Focus on visual cues, layout, icons, and UI elements. Make the guide suitable for deaf users.`
            }
          ],
          temperature: 0.7,
          max_tokens: 1000,
          response_format: { type: "json_object" }
        });

        const content = response.choices[0].message.content;
        const parsedContent = JSON.parse(content);
        
        if (Array.isArray(parsedContent.steps)) {
          return parsedContent.steps;
        }
        
        // If the response isn't formatted correctly, return an empty array
        return [];
      } catch (error) {
        console.error('Error generating visual steps with OpenAI:', error);
        return [];
      }
    }
    
    // Fallback when OpenAI is not available and we don't have predefined steps
    return [];
  }

  async generateCustomGuidance(feature: string, context: string, isDeaf: boolean = false): Promise<string> {
    // If OpenAI is not available, return an error message
    if (!openai) {
      return "Custom guidance generation is currently unavailable. Please try again later.";
    }
    
    try {
      const prompt = isDeaf
        ? `Create a customized, visually-focused explanation of the security feature "${feature}" specifically for deaf users, considering this additional context: "${context}". Use the phrase "VISUAL EXPLANATION:" followed by a bullet list of how the feature works visually. Focus on what users will see on screen and how visual cues indicate the feature is working. Avoid auditory descriptions.`
        : `Create a customized explanation of the security feature "${feature}" considering this additional context: "${context}". Explain what it is, how it works, and why it's important for security. Keep the explanation under 250 words and focus on plain language without technical jargon.`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o", // the newest OpenAI model is "gpt-4o" which was released May 13, 2024. do not change this unless explicitly requested by the user
        messages: [
          { 
            role: "system", 
            content: "You are an accessibility specialist who explains security concepts clearly and adapts explanations to specific contexts."
          },
          { 
            role: "user", 
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 800
      });

      return response.choices[0].message.content;
    } catch (error) {
      console.error('Error generating custom guidance with OpenAI:', error);
      return "We couldn't generate a custom explanation at this time. Please try again later.";
    }
  }
}

export const accessibilityService = new AccessibilityService();